name: Java CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
            https://github.com/xXSchrandXx/SpigotPlugins/commits/master
          draft: false
          prerelease: false
      - name: Upload SchrandAPI
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/SpigotPlugins/SpigotPlugins/SchrandAPI/target/SchrandAPI.jar
          asset_name: SchrandAPI.jar
          asset_content_type: application/jar
      - name: Upload AsyncWorldManager
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/SpigotPlugins/SpigotPlugins/AsyncWorldManager/target/AsyncWorldManager.jar
          asset_name: AsyncWorldManager.jar
          asset_content_type: application/jar
      - name: Upload NetherPortalGate
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/SpigotPlugins/SpigotPlugins/NetherPortalGate/target/NetherPortalGate.jar
          asset_name: NetherPortalGate.jar
          asset_content_type: application/jar
      - name: Upload ServerStatusSign
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/work/SpigotPlugins/SpigotPlugins/ServerStatusSign/target/ServerStatusSign.jar
          asset_name: ServerStatusSign.jar
          asset_content_type: application/jar
