name: Build and Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JacksonMaxfield/github-pages-deploy-action-python@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: master
        FOLDER: docs/_build/html
        BUILD_SCRIPT: pip install .[all] && make docs-build && docs/make_index.py /docs/